[build]
root = "src"
outdir = "dist"

[test]
# Tests are colocated with source files
root = "src"
coverage = false
coverageDir = "./coverage"

[package]
# Allow importing from web package
workspaces = ["web"]
