[build]
root = "src"
outdir = "dist"

[test]
# Tests are colocated with source files, plus e2e tests
root = "."
coverage = true
coverageDir = "./coverage"
coverage_threshold = 80
coverage_reporter = ["text", "lcov", "html"]

[package]
# Allow importing from web package
workspaces = ["web"]
