apiVersion: monitoring.yuptime.io/v1
kind: Monitor
metadata:
  name: test-disabled
  namespace: yuptime
spec:
  type: http
  enabled: false
  schedule:
    intervalSeconds: 30
    timeoutSeconds: 10
  target:
    http:
      url: "https://www.google.com"
