apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: timoni
    app.kubernetes.io/name: {{ include "yuptime.fullname" . }}
    app.kubernetes.io/version: 0.0.0-devel
  name: {{ include "yuptime.fullname" . }}-checker
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "yuptime.fullname" . }}-checker
subjects:
- kind: ServiceAccount
  name: {{ include "yuptime.fullname" . }}-checker
  namespace: {{ .Release.Namespace }}