apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/managed-by: timoni
    app.kubernetes.io/name: {{ include "yuptime.fullname" . }}
    app.kubernetes.io/version: 0.0.0-devel
  name: {{ include "yuptime.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
stringData:
  admin-password-hash: $argon2id$v=19$m=65536,t=3,p=4$Ha7NhMrOOSle+AMHOp5XNw$jhFoCy75xBnmZJY+FKPujTeFg26xnR1wfDwFJJVrBhU
  session-secret: dev-secret-change-in-production
type: Opaque