apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: timoni
    app.kubernetes.io/name: {{ include "yuptime.fullname" . }}
    app.kubernetes.io/version: 0.0.0-devel
  name: {{ include "yuptime.fullname" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: timoni
    app.kubernetes.io/name: {{ include "yuptime.fullname" . }}
    app.kubernetes.io/version: 0.0.0-devel
  name: {{ include "yuptime.fullname" . }}-checker
  namespace: {{ .Release.Namespace }}